name: Android CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./SWEN766BetterMaps
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # - name: Set up Android SDK
    #   uses: android-actions/setup-android@v2
    #   with:
    #     api-level: 30
    #     target: android-30
    #     build-tools: 30.0.3
    #     ndk: 23.1.7779620

    # - name: Start Emulator
    #   run: |
    #     echo "y" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "system-images;android-30;google_apis;x86_64"
    #     $ANDROID_SDK_ROOT/emulator/emulator -avd test -no-snapshot-load -no-window -no-audio &
    #   timeout-minutes: 5

    # - name: Wait for Emulator
    #   run: |
    #     adb wait-for-device
    #     adb shell input keyevent 82
    #   timeout-minutes: 3

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run Unit Tests
      run: ./gradlew testReleaseUnitTest
    # - name: Run Instrumented Tests
    #   run: ./gradlew connectedAndroidTest
