name: Android CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./SWEN766BetterMaps
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Update Android SDK Command-Line Tools
      run: |
        sdkmanager --update
        sdkmanager --install "cmdline-tools;latest"

    - name: Install Android Emulator
      run: |
        sdkmanager "platform-tools" "platforms;android-33" "system-images;android-33;google_apis;x86_64" "emulator"
    

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    # - name: Build with Gradle
    #   run: ./gradlew build
    - name: Run Unit Tests
      run: ./gradlew testReleaseUnitTest

    - name: Run Instrumented Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 34
        target: google_apis
        script: ./gradlew connectedAndroidTest
